version: '3.9'

services:
  nginx:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
        args:
            user: webcomcafe
            uid: 1001
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/usr/share/nginx
      - .infra/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-net
  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - .infra/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
